### ISSUE TITLE
Builds start failing after merge fail

### ISSUE THREAD

**Issue by timn** [seek-oss/github-merged-pr-buildkite-plugin#14]
A PR was filed that contained a merge conflict. This caused the build to fail, since this plugin could not perform the merge. The build fail is ok.

The problem then occurs when performing the next build, it also fails. The reason is, that the source repository is left in an unclean state with unmerged paths. This causes later merges with the message "error: you need to resolve your current index first".

The proper fix would be to properly cleanup the repository after a merge conflict, maybe this could be as simple as ```git merge --abort```.

**Comment by zsims** [comment]
Good pickup! Will look at aborting the merge if it fails

**Comment by zsims** [comment]
#16 fixed this, and should be available in release `v0.0.8`: https://github.com/seek-oss/github-merged-pr-buildkite-plugin/releases/tag/v0.0.8
